package com.sipfront.sdk.json.enums

/**
 * This is a JavaScript wrapper for [MessageType]
 *
 * Required because KMM cannot yet convert Enums to JavaScript code
 *
 * @since 1.0.6
 * @author Dominik Ridjic
 */
@Suppress("NON_EXPORTABLE_TYPE")
@OptIn(ExperimentalJsExport::class)
@JsExport
object MessageTypeJs {
    val RTCP = MessageType.Rtcp.RTCP
    val SIP_OUTGOING = MessageType.Sip.OUTGOING
    val SIP_INCOMING = MessageType.Sip.INCOMING
    val SDP_OUTGOING = MessageType.Sdp.OUTGOING
    val SDP_INCOMING = MessageType.Sdp.INCOMING
    val STATE_CREATE = MessageType.State.CREATE
    val STATE_REGISTER = MessageType.State.REGISTER
    val STATE_REGISTER_FAILED = MessageType.State.REGISTER_FAILED
    val STATE_REGISTERING = MessageType.State.REGISTERING
    val STATE_UNREGISTERING = MessageType.State.UNREGISTERING
    val STATE_FALLBACK_OK = MessageType.State.FALLBACK_OK
    val STATE_FALLBACK_FAILED = MessageType.State.FALLBACK_FAILED
    val STATE_MWI_NOTIFY = MessageType.State.MWI_NOTIFY
    val STATE_SHUTDOWN = MessageType.State.SHUTDOWN
    val STATE_EXIT = MessageType.State.EXIT
    val STATE_SIP_SESSION_CONNECTED = MessageType.State.SIP_SESSION_CONNECTED
    val STATE_CALL_POST_DIAL_DELAY = MessageType.State.CALL_POST_DIAL_DELAY
    val STATE_CALL_INCOMING = MessageType.State.CALL_INCOMING
    val STATE_CALL_OUTGOING = MessageType.State.CALL_OUTGOING
    val STATE_CALL_RINGING = MessageType.State.CALL_RINGING
    val STATE_CALL_PROGRESS = MessageType.State.CALL_PROGRESS
    val STATE_CALL_ANSWERED = MessageType.State.CALL_ANSWERED
    val STATE_CALL_ANSWERING = MessageType.State.CALL_ANSWERING
    val STATE_CALL_ANSWER_DELAY = MessageType.State.CALL_ANSWER_DELAY
    val STATE_CALL_ESTABLISHED = MessageType.State.CALL_ESTABLISHED
    val STATE_CALL_RTP_ESTABLISHED = MessageType.State.CALL_RTP_ESTABLISHED
    val STATE_CALL_LOCAL_SDP = MessageType.State.CALL_LOCAL_SDP
    val STATE_CALL_REMOTE_SDP = MessageType.State.CALL_REMOTE_SDP
    val STATE_CALL_ENDED_LOCAL = MessageType.State.CALL_ENDED_LOCAL
    val STATE_CALL_ENDED_REMOTE = MessageType.State.CALL_ENDED_REMOTE
    val STATE_CALL_REJECTED = MessageType.State.CALL_REJECTED
    val STATE_CALL_FAILED = MessageType.State.CALL_FAILED
    val STATE_CALL_BUSY_HERE = MessageType.State.CALL_BUSY_HERE
    val STATE_CALL_TEMPORARILY_UNAVAILABLE = MessageType.State.CALL_TEMPORARILY_UNAVAILABLE
    val STATE_CALL_FORBIDDEN = MessageType.State.CALL_FORBIDDEN
    val STATE_CALL_NOT_ACCEPTABLE = MessageType.State.CALL_NOT_ACCEPTABLE
    val STATE_CALL_NOT_FOUND = MessageType.State.CALL_NOT_FOUND
    val STATE_CALL_DECLINE = MessageType.State.CALL_DECLINE
    val STATE_CALL_CANCEL = MessageType.State.CALL_CANCEL
    val STATE_CALL_UNAUTHORIZED = MessageType.State.CALL_UNAUTHORIZED
    val STATE_CALL_PROXY_AUTHENTICATION_REQUIRED = MessageType.State.CALL_PROXY_AUTHENTICATION_REQUIRED
    val STATE_CALL_CLOSED = MessageType.State.CALL_CLOSED
    val STATE_CALL_IN_PROGRESS = MessageType.State.CALL_IN_PROGRESS
    val STATE_CALL_HOLD = MessageType.State.CALL_HOLD
    val STATE_CALL_RESUME = MessageType.State.CALL_RESUME
    val STATE_CALL_HOLD_LOCAL = MessageType.State.CALL_HOLD_LOCAL
    val STATE_CALL_RESUME_LOCAL = MessageType.State.CALL_RESUME_LOCAL
    val STATE_CALL_TRANSFER = MessageType.State.CALL_TRANSFER
    val STATE_CALL_TRANSFER_FAILED = MessageType.State.CALL_TRANSFER_FAILED
    val STATE_CALL_REDIRECT = MessageType.State.CALL_REDIRECT
    val STATE_CALL_DTMF_START = MessageType.State.CALL_DTMF_START
    val STATE_CALL_DTMF_0 = MessageType.State.CALL_DTMF_0
    val STATE_CALL_DTMF_1 = MessageType.State.CALL_DTMF_1
    val STATE_CALL_DTMF_2 = MessageType.State.CALL_DTMF_2
    val STATE_CALL_DTMF_3 = MessageType.State.CALL_DTMF_3
    val STATE_CALL_DTMF_4 = MessageType.State.CALL_DTMF_4
    val STATE_CALL_DTMF_5 = MessageType.State.CALL_DTMF_5
    val STATE_CALL_DTMF_6 = MessageType.State.CALL_DTMF_6
    val STATE_CALL_DTMF_7 = MessageType.State.CALL_DTMF_7
    val STATE_CALL_DTMF_8 = MessageType.State.CALL_DTMF_8
    val STATE_CALL_DTMF_9 = MessageType.State.CALL_DTMF_9
    val STATE_CALL_DTMF_A = MessageType.State.CALL_DTMF_A
    val STATE_CALL_DTMF_B = MessageType.State.CALL_DTMF_B
    val STATE_CALL_DTMF_C = MessageType.State.CALL_DTMF_C
    val STATE_CALL_DTMF_D = MessageType.State.CALL_DTMF_D
    val STATE_CALL_DTMF_ASTERISK = MessageType.State.CALL_DTMF_ASTERISK
    val STATE_CALL_DTMF_POUND = MessageType.State.CALL_DTMF_POUND
    val STATE_CALL_DTMF_END = MessageType.State.CALL_DTMF_END
    val STATE_CALL_SEND_DTMF_START = MessageType.State.CALL_SEND_DTMF_START
    val STATE_CALL_SEND_DTMF_0 = MessageType.State.CALL_SEND_DTMF_0
    val STATE_CALL_SEND_DTMF_1 = MessageType.State.CALL_SEND_DTMF_1
    val STATE_CALL_SEND_DTMF_2 = MessageType.State.CALL_SEND_DTMF_2
    val STATE_CALL_SEND_DTMF_3 = MessageType.State.CALL_SEND_DTMF_3
    val STATE_CALL_SEND_DTMF_4 = MessageType.State.CALL_SEND_DTMF_4
    val STATE_CALL_SEND_DTMF_5 = MessageType.State.CALL_SEND_DTMF_5
    val STATE_CALL_SEND_DTMF_6 = MessageType.State.CALL_SEND_DTMF_6
    val STATE_CALL_SEND_DTMF_7 = MessageType.State.CALL_SEND_DTMF_7
    val STATE_CALL_SEND_DTMF_8 = MessageType.State.CALL_SEND_DTMF_8
    val STATE_CALL_SEND_DTMF_9 = MessageType.State.CALL_SEND_DTMF_9
    val STATE_CALL_SEND_DTMF_A = MessageType.State.CALL_SEND_DTMF_A
    val STATE_CALL_SEND_DTMF_B = MessageType.State.CALL_SEND_DTMF_B
    val STATE_CALL_SEND_DTMF_C = MessageType.State.CALL_SEND_DTMF_C
    val STATE_CALL_SEND_DTMF_D = MessageType.State.CALL_SEND_DTMF_D
    val STATE_CALL_SEND_DTMF_ASTERISK = MessageType.State.CALL_SEND_DTMF_ASTERISK
    val STATE_CALL_SEND_DTMF_POUND = MessageType.State.CALL_SEND_DTMF_POUND
    val STATE_CALL_SEND_DTMF_END = MessageType.State.CALL_SEND_DTMF_END
    val STATE_CALL_MENC = MessageType.State.CALL_MENC
    val STATE_VU_TX = MessageType.State.VU_TX
    val STATE_VU_RX = MessageType.State.VU_RX
    val STATE_AUDIO_ERROR = MessageType.State.AUDIO_ERROR
    val STATE_AUDIO_LATENCY_OUTGOING = MessageType.State.AUDIO_LATENCY_OUTGOING
    val STATE_AUDIO_LATENCY_INCOMING = MessageType.State.AUDIO_LATENCY_INCOMING
    val STATE_FAX_SUCCESS = MessageType.State.FAX_SUCCESS
    val STATE_FAX_FAILED = MessageType.State.FAX_FAILED
    val STATE_FAXMODE_AUDIO = MessageType.State.FAXMODE_AUDIO
    val STATE_FAXMODE_T38 = MessageType.State.FAXMODE_T38
    val STATE_PHONE_ATTACHED = MessageType.State.PHONE_ATTACHED
    val STATE_PHONE_DETACHED = MessageType.State.PHONE_DETACHED
    val STATE_PHONE_SELECTED = MessageType.State.PHONE_SELECTED
    val STATE_PHONE_PROPERTY_CHANGED = MessageType.State.PHONE_PROPERTY_CHANGED
    val STATE_HANDSFREE_PROPERTY_CHANGED = MessageType.State.HANDSFREE_PROPERTY_CHANGED
    val STATE_CALLVOLUME_CHANGED = MessageType.State.CALLVOLUME_CHANGED
    val STATE_CALL_REMOVED = MessageType.State.CALL_REMOVED
    val STATE_CALL_HELD = MessageType.State.CALL_HELD
    val STATE_CALL_WAITING = MessageType.State.CALL_WAITING
    val STATE_CALL_STATE_CHANGED = MessageType.State.CALL_STATE_CHANGED
    val STATE_CALL_PROPERTY_CHANGED = MessageType.State.CALL_PROPERTY_CHANGED
    val STATE_CALL_DISCONNECTED = MessageType.State.CALL_DISCONNECTED
    val STATE_CALLMANAGER_PROPERTY_CHANGED = MessageType.State.CALLMANAGER_PROPERTY_CHANGED
    val STATE_CALLMANAGER_BARRING_ACTIVE = MessageType.State.CALLMANAGER_BARRING_ACTIVE
    val STATE_CALLMANAGER_FORWARDED = MessageType.State.CALLMANAGER_FORWARDED
}
